# ======================================================
# Configurações Comuns a Todos os Perfis
# ======================================================

spring:
  # Configurações gerais da aplicação
  application:
    name: clientes-api
  profiles:
    active: dev

  # Configurações do JPA (iguais para ambos os perfis)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuração do Console H2
  h2:
    console:
      enabled: true
      path: /h2-console

# ======================================================
# Configuração do JWT (fora do bloco spring)
# ======================================================
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}