spring:
  application:
    name: clientes-api

  profiles:
    active: dev   # padrão é dev, mas você pode trocar para prod com --spring.profiles.active=prod

---

# Perfil de desenvolvimento (H2)
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:clientesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza tabelas automaticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

---

# Perfil de produção (PostgreSQL)
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/clientesdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
